config/routes.rb
Rails.application.routes.draw do
  resources :ranks

end

app/models/rank.rb
class Rank < ActiveRecord::Base
  validates :name, presence: true
  validate :score_to_greater, :not_over_lapping

  private

  def score_to_greater
    if score_from >= score_to
        errors.add(:bad_Score, 'score_to must be larger then score_from')
  end


  def not_over_lapping
    if(!Rank.where("(? >= score_from AND ? <= score_to) OR (? >= score_from AND ? <= score_to)", score_from, score_from, score_to, score_to).empty?)
        errors.add(:overlapping, 'the score is overlapping with some of the other scores')
  end
  end
  end
  end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/ranks_controller.rb
class RanksController < ApplicationController
  before_action :set_rank, only: [:show, :edit, :update, :destroy]

  # GET /ranks
  def index
    @ranks = Rank.all
  end

  # GET /ranks/1
  def show
  end

  # GET /ranks/new
  def new
    @rank = Rank.new
  end

  # GET /ranks/1/edit
  def edit
  end

  # POST /ranks
  def create
    @rank = Rank.new(rank_params)

    if @rank.save
      redirect_to @rank, notice: 'Rank was successfully created.'
    else
      flash[:alert] = @rank.errors.full_messages.join(", ")
      render :new
    end
  end

  # PATCH/PUT /ranks/1
  def update
    if @rank.update(rank_params)
      redirect_to @rank, notice: 'Rank was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /ranks/1
  def destroy
    @rank.destroy
    redirect_to ranks_url, notice: 'Rank was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rank
      @rank = Rank.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def rank_params
      params.require(:rank).permit(:score_from, :score_to, :name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ranks_helper.rb
module RanksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SampleApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <nav class="navbar navbar-default">
    <div class="container-fluid">
      <div class="navbar-header">
        <a class="navbar-brand" href="#">
          SampleApp
        </a>
      </div>
    </div>
  </nav>

  <div class="container-fluid">
    <%= yield %>
  </div>

</body>
</html>

app/views/ranks/_form.slim
- if flash[:alert]
  .alert.alert-danger
    = flash[:alert]

= simple_form_for(@rank, html: { class: 'form-horizontal' }) do |f|
  = f.input :score_from
  = f.input :score_to
  = f.input :name
  = f.button :submit

hr

app/views/ranks/edit.slim
.row
  .col-md-6
    .panel.panel-default
      .panel-heading
        h3.panel-title Edit Rank
      .panel-body
        = render 'form'
        = link_to 'Show', @rank, class: 'btn btn-primary'
        = link_to 'Back', ranks_path, class: 'btn btn-default'

app/views/ranks/index.slim
.row
  .col-md-12
    .panel.panel-default
      .panel-heading
        h3.panel-title Listing Ranks
      .panel-body
        table.table.table-striped
          thead
            tr
              th Score from
              th Score to
              th Name
              th colspan="3"
          tbody
            - @ranks.each do |rank|
              tr
                td= rank.score_from
                td= rank.score_to
                td= rank.name
                td= link_to 'Show', rank
                td= link_to 'Edit', edit_rank_path(rank)
                td= link_to 'Destroy', rank, method: :delete, data: { confirm: 'Are you sure?' }
        br/
        = link_to 'New Rank', new_rank_path, class: 'btn btn-primary'

app/views/ranks/new.slim
.row
  .col-md-6
    .panel.panel-default
      .panel-heading
        h3.panel-title New Rank
      .panel-body
        = render 'form'
        = link_to 'Back', ranks_path

app/views/ranks/show.slim
.row
  .col-md-6
    .panel.panel-default
      .panel-heading
        h3.panel-title
          | Rank:
          = @rank.name
      .panel-body
        p
          strong Score from:
          = @rank.score_from
        p
          strong Score to:
          = @rank.score_to
        p
          strong Name:
          = @rank.name
        = link_to 'Edit', edit_rank_path(@rank), class: 'btn btn-default'
        = link_to 'Back', ranks_path, class: 'btn btn-default'